### ISSUE TITLE
Evento para sinalizar que 'channel' está pronto.

### ISSUE THREAD

**Issue by claudiokoji** [TOTVSTEC/cloudbridge-cli#2]
Quando a aplicação inicia, há a troca de mensagens entre cloudbridge e js para criar o componente **'channel'**, que servirá de gateway para envio de mensagens.

Porém, esta criação não é instantânea. Por exemplo, tomando por base o app base gerado com o cli, se eu inserir uma tag script logo após o insert do arquivo totvs-twebchannel.js, a mensagem nunca chega ao servidor:

```
<script src="bower/totvs-twebchannel/totvs-twebchannel.js"></script>

<script>
	channel.getPicture(function cb() {});
</script>
```

Para que a mensagem chegue, é necessário inserir o comando dentro de um timeout:

```
<script src="bower/totvs-twebchannel/totvs-twebchannel.js"></script>

<script>
	setTimeout(function(){
		channel.getPicture(function cb() {});
	},3000);
</script>
```

Não sei qual o tempo necessário (coloquei 3s para teste).

O problema é que no modelo do mingle (e acredito que na maioria dos apps que vamos criar), uma chamada ao **channel** deve ser feita logo no início (para pegar os dados do usuário que estão no SQLite), e fazer isso com um timeout vai atrasar ainda mais a inicialização.

Sugestão: Disparar um evento assim que o componente channel for carregado, indicado que está tudo pronto para ser usado (similar ao cordova deviceReady https://cordova.apache.org/docs/en/4.0.0/cordova/events/events.deviceready.html).

**Comment by rogeriorc** [comment]
#
